### ISSUE TITLE
Styling rules differ per file

### ISSUE THREAD

**Issue by bear-in-a-box** [Chester97/genesis-app#3]
Comparing project's files exposes an issue with code styling. There are cases where one file uses single quotes for strings, while another one uses double quotes. Semicolons are missing in some places, though it looks like assumed styling convention is to use them everywhere.
I'd suggest using ESLint + Prettier at least, so that you can get ESLint's feedback immediately as you type and make use of "format file on save" magic provided by Prettier.

**Comment by bear-in-a-box** [comment]
If you wanted to step the game up, you would add husky and lint-staged to your dependencies as well. This would allow you to create pre-commit hook easily and perform style checking automatically.

**Comment by Chester97** [comment]
Done. I've added esLint with airbnb guides and some small changes in rules, but I haven't resolve all of the errors yet.
